### ISSUE TITLE
Improve default formatting of Special:Browse data

### ISSUE THREAD

**Issue by krabina** [gesinn-it-pub/mediawiki-extensions-SemanticDrilldown#14]
By default, the category table is shown on the rigt which is not formatted nicely. Also, if you have a table as display format with bootstrap class "table table-hover sortable" it will only show below the category table.

![grafik](https://user-images.githubusercontent.com/4318745/188491387-57b22c1b-70b4-44f0-970c-41b1aae18bea.png)

This could be formatted more elegantly.

**Comment by gesinn-it-gea** [comment]
fix to remove margin and padding: c1b13e7f1ed2c6f7a7b80523b5fe636c921c06db

**Comment by gesinn-it-gea** [comment]
Try "table" instead of "broadtable" to make the table float "left" of categories

**Comment by krabina** [comment]
did not use "broadtable", but added the bootstrap classes "table". I like the tabs better anyway.

**Comment by gesinn-it-gea** [comment]
Check if the final html/css for the table contains a fixed width. For broadtable, 100% is set. This leads to the effect shown in your screenshot.
